export const cardData = [
    {
        id: 1,
        backgroundColor: "white",
        img:"/images/pic1.webp",
        title: "Hoodies & Sweatshirts",
        price:"$50.22",
        rating:2,
        
    },
    {
        id: 2,
        backgroundColor: "white",
        img:"/images/pic2.png",
        title: "Coats & Parkas",
        price:"$10.20",
        rating:3,
    },
    {
        id: 3,
        backgroundColor: "white",
        img:"/images/pic3.png",
        title: "Tees & T-Shirts",
        price:"$15.45",
        rating:4,
    },
    {
        id: 4,
        backgroundColor: "white",
        img:"/images/pic4.webp",
        title: "Sleeveless Hoodies",
        price:"$20.11",
        rating:3,
    },
    {
        id: 5,
        backgroundColor: "white",
        img:"/images/pic8.webp",
        title: "Henley shirts",
        price:"$20.22",
        rating:5
    },
    {
        id: 6,
        backgroundColor: "white",
        img:"/images/pic5.jpg",
        title: "Crewneck & Sweaters",
        price:"$10.00",
        rating:4,
    },
    {
        id: 7,
        backgroundColor: "white",
        img:"/images/pic6.webp",
        title: "Graphic tees",
        price:"$55.45",
        rating:4,
    },
    {
        id: 8,
        backgroundColor: "white",
        img:"/images/pic7.webp",
        title: "Crewneck & Sweaters",
        price:"$10.50",
        rating:3,
    },
    {
        id: 9,
        backgroundColor: "white",
        img:"/images/pic10.jpg",
        title: "Polo Shirts",
        price:"$40.20",
        rating:3,
    },
    {
        id: 10,
        backgroundColor: "white",
        img:"/images/pic9.jpg",
        title: "Cardigans",
        price:"$20.03",
        rating:2,
    },
    {
        id:11,
        backgroundColor: "white",
        img:"/images/pic11.webp",
        title: "V-Neck Sweaters",
        price:"$30.50",
        rating:4,
    },
    {
        id: 12,
        backgroundColor: "white",
        img:"/images/pic12.webp",
        title: "Zip-Up Hoodies",
        price:"$17.70",
        rating:5,
    },
    {
        id: 13,
        backgroundColor: "white",
        img:"/images/pic13.jpg",
        title: "Flannel Shirts",
        price:"$16.75",
        rating:3,
    },
    {
        id: 14,
        backgroundColor: "white",
        img:"/images/pic15.webp",
        title: "Long-sleeve t-shirts",
        price:"$28.60",
        rating:2,
    },
    {
        id: 15,
        backgroundColor: "white",
        img:"/images/pic16.jpg",
        title: "Tank Tops",
        price:"$30.20",
        rating:1,
    },
    {
        id: 16,
        backgroundColor: "white",
        img:"/images/pic17.webp",
        title: "Puffer Vest",
        price:"$38.60",
        rating:3,
    }
]